import {
  Avatar,
  Box,
  Flex,
  Heading,
  HStack,
  Icon,
  Image,
  Text,
  VStack,
} from "@chakra-ui/react";
import Head from "next/head";
import { BiUser, BiCodeBlock } from "react-icons/bi";
import {
  MdOutlineStickyNote2,
  MdOutlineOndemandVideo,
  MdAnimation,
  MdOutlineBookmarkBorder,
} from "react-icons/md";
import { GiPalette } from "react-icons/gi";
import { Tb3DCubeSphere, TbWritingSign, TbBulb } from "react-icons/tb";
import SpecialtyIcon from "../components/atoms/PrimaryIcon";
import { RiShieldUserLine } from "react-icons/ri";
import ProjectIndex from "../components/organisms/projects/ProjectIndex";
import { BsFillPinFill } from "react-icons/bs";
import SpecialtyIcons from "../components/molecules/SpecialtyIcons";
import TagIcons from "../components/molecules/TagIcons";
import PrimaryFind from "../components/atoms/PrimaryFind";
import Labels from "../components/molecules/Labels";
import ProductCard from "../components/molecules/ProductCard";
import { HiBookOpen } from "react-icons/hi";
import { GrGroup } from "react-icons/gr";
// import UserInfoCard from "../components/molecules/users/UserInfoCard";
import { useRouter } from "next/router";
import DashboardItemContainer from "../components/organisms/DashboardItemContainer";
import UserInfoCard from "../components/molecules/users/UserInfoCard";
import { useCollection, useDocumentData } from "react-firebase-hooks/firestore";
import { collection, doc } from "firebase/firestore";
import { db } from "../firebase/config";
import { AuthContext } from "./_app";
import React from "react";
import Dashboard from "../components/templates/Dashboard";
import Top from "../components/templates/Top";

const Home = () => {
  const router = useRouter();
  const { currentUser } = React.useContext(AuthContext);

  const [usersSnapshot] = useCollection(collection(db, "users"));
  const users = usersSnapshot?.docs.map((doc) => ({
    id: doc.id,
    ...doc.data(),
  }));

  const user = users?.find((user) => user.id === currentUser?.uid);

  console.log("currentUser", currentUser);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex
        h="100%"
        w="100%"
        overflowX="scroll"
        direction="column"
        alignItems="center"
        pb="80px"
      >
        <Flex
          direction="column"
          w={currentUser?.uid ? "800px" : "100%"}
          mx={currentUser?.uid ? "40px" : 0}
          mt={currentUser?.uid ? "40px" : 0}
        >
          {/* ここに中身を記述 */}
          {currentUser?.uid ? <Dashboard /> : <Top />}
        </Flex>
      </Flex>
    </>
  );
};

export default Home;
